# Generated by Django 4.0.3 on 2022-04-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choise',
        ),
    ]
